### ISSUE TITLE
Translate acronyms and make text nice before displaying to user

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#10]
![image](https://github.com/ericnost/streamlit_test/assets/454690/53919853-0a79-47cd-ad47-b6b7370295ad)
 e.g. should have names in nice case, acronyms spelled out, bonus points if we can make it a table.

**Comment by ericnost** [comment]
This is where some of these parameters / formatting can be changed: https://github.com/ericnost/streamlit_test/blob/55dcf01f09f2780b7932a5c9600956e4caffb2df/pages/1_%F0%9F%8C%8D_Statewide_Overview.py#L46

**Comment by Frijol** [comment]
Thanks, I have it going in a branch already! Ha trying to get the text wrapping nice before I PR since all the names are long now
