### ISSUE TITLE
Mapping violations of colocated facilities

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#112]
I like the new color scale, but the handling of multiple facilities is a bit confusing, especially from a color perspective.

![image](https://github.com/ericnost/streamlit_test/assets/454690/4d419f8b-310d-4c27-a948-83f2c791a3b1)

Could we maye just show the spiral version without needing to click? I think it would give an accurate visual impression of the number of violations in an area. Would be ok to make the circles smaller if that makes this easier.

![image](https://github.com/ericnost/streamlit_test/assets/454690/90231401-cd21-4849-81c8-eeace5a981a6)

_Originally posted by @Frijol in https://github.com/ericnost/streamlit_test/issues/89#issuecomment-1656480673_

**Comment by ericnost** [comment]
Looking at some of the options, I'm not sure there's a way to show the spirals by default (without clicking) but there are some custom styling options for clusters (if we can't get the spirals to show by default): https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-custom.html
https://github.com/Leaflet/Leaflet.markercluster#all-options
