### ISSUE TITLE
Box drawing error should be more obvious

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#12]
Not sure what's most plausible, but some ideas:
* Box unwilling to grow past a certain size (stops growing and starts to drag, turns red and won't make a box, etc.)
* Box is a resizable element that won't resize past a certain amount
* Error pops up as toast element or otherwise somewhere on top of the map area

**Comment by ericnost** [comment]
Another idea that occurred to me would be to have a default box that is more or less the largest size possible, to give users a sense of what they should be aiming for, and also to give them the possibility of navigating through the app at first without making any choices, to see what it does.

**Comment by Frijol** [comment]
I like that a lot, actually - especially if it could be cached as a default, dragged around, resized

**Comment by ericnost** [comment]
💯 yea, that's the idea! I'll try experimenting with it....
