### ISSUE TITLE
issue with alignment of maps on statewide overview?

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#123]
On my large screen, the PWS map (circles) isn't left-justified in line with the PSA black outlines map:

<img width="1804" alt="image" src="https://github.com/ericnost/streamlit_test/assets/6888951/c2eae346-b38e-4309-a9c3-dbcca9dd2ea5">

Maybe this is intentional, maybe not - I think they're both supposed to be on the left, one after the other?

**Comment by Frijol** [comment]
Oh, yeah, it seems to do this sometimes as a loading issue. Very weird handling of containers imo. When it loads properly it looks like this: 
![image](https://github.com/ericnost/streamlit_test/assets/454690/3b51e466-0571-44af-8b6c-6cc86d368273)

**Comment by Frijol** [comment]
idk if we can fix, they are already in entirely separate containers. Tried renaming the columns in case of variable collision but it didn't seem to help.

**Comment by ericnost** [comment]
@Frijol Ok, I think I spotted the issue. Columns within columns, I think. Here's what I get with my fix:  
<img width="1371" alt="image" src="https://github.com/ericnost/streamlit_test/assets/6888951/3210b48b-adc4-4c90-8945-d7240c70aed3">
