### ISSUE TITLE
Loading warning should show as part of the element that's loading

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#13]
Instead of blankness, there should be some kind of loading icon/text that loads fast and shows while the main element is still loading, then disappears once loading completes

**Comment by ericnost** [comment]
Indeed, though I've been relying on the default Streamlit "Running" icon in the upper right-hand side of the screen.

**Comment by Frijol** [comment]
This is a nice easy fix: https://docs.streamlit.io/library/api-reference/status/st.spinner

Implemented in https://github.com/ericnost/streamlit_test/pull/20
