### ISSUE TITLE
Load data on whatever page people go to first?

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#18]
I'm wondering if we could do the st.cache_data call on whatever page a user hits first (with some kind of if call to see if it's already cached) to speed up loading & make an easier flow

**Comment by ericnost** [comment]
But maybe the idea is that we load the data in the background of Welcome.py and make it available to the other pages? That's definitely worth a try. I wonder if we can load it on Welcome.py without stopping the text from loading.

**Comment by Frijol** [comment]
Yes, I definitely think loading on Welcome.py would be good! Anywhere where people have something to do/read while waiting.

I think Streamlit does a good job loading elements as they are ready, so suspect as long as the code is after the text it should load text ok.

Re arriving at the other pages, I can imagine a sharing scenario, someone is trying to show a friend something specific. But of course bc most of it does rely on the selected area, it's a bit moot unless that also becomes e.g. a url query param.

Also wondering if we might treat the area selection the same way as the caching: if it's selected, it shows on the map; if it's not selected, it prompts you.

Specifically for the student usage idea, imagining the teacher wants to send the link to a specific module, so they can just discuss that part with their students (e.g. lead lines). More user control to choose a pathway through the content is helpful.

**Comment by Frijol** [comment]
Now that there's a default area for EJ violations, do people really need to go to the SDWA page first?

**Comment by ericnost** [comment]
Well, they need to go to the SDWA page first to have the data for the default area loaded....However, I could see some sort of check on each page (including Welcome) that sees if the full data / default area data are loaded. If not, it loads them there. If already loaded, or a custom area has been drawn and that data loaded, no error. I would just want to map out all of the possible scenarios first before testing.

**Comment by ericnost** [comment]
Frankly, I'm not sure I'm smart enough to understand Streamlit's session states to make this data loading approach work (see the struggle in #56)
