### ISSUE TITLE
Key for PWS locations map

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#22]
What do the different shades of orange mean?

Should we make different circle sizes for different size designations?

Can we indicate size, source, and type using the size, fill, and outline?

**Comment by ericnost** [comment]
There's only one shade of orange but it's semi-transparent and there are some facilities stacked on top of one another, giving the appearance of different shades.

Yes, we could do different circle sizes for the different size designations - I had considered that. It's a great idea.

How about:

size = `POPULATION_SERVED_COUNT`
colour = type (CWS, NTNCWS, TCWS)
outline - dashed/solid = groundwater vs surface water

?

Would need to create a legend to that effect too.

**Comment by ericnost** [comment]
This is where some of these parameters can be changed (at least for the overview page): https://github.com/ericnost/streamlit_test/blob/55dcf01f09f2780b7932a5c9600956e4caffb2df/pages/1_%F0%9F%8C%8D_Statewide_Overview.py#L46

**Comment by Frijol** [comment]
Yes love it!
