### ISSUE TITLE
Additional context on EJ indicators

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#29]
Would be great to add in a table of the official meanings of the EJ indicators with a bit more context from https://www.epa.gov/ejscreen/overview-socioeconomic-indicators-ejscreen

**Comment by ericnost** [comment]
💯 (though not all of the EJ indicators are spelled out, just the socioeconomic ones, while we also include some of the other environmental variables like Ozone. But we probably shouldn't? Why would ozone matter - cumulative impacts?)

**Comment by Frijol** [comment]
Yeah, I find it super confusing that the environmental and the socioeconomic indicators are lumped together generally. Maybe we should focus just on the socioeconomic and filter out the environmental ones for greater clarity.

**Comment by Frijol** [comment]
I do have technical definitions for e.g. Ozone as well, though, if we did want to keep them: "Annual average of top ten maximum daily 8-hour ozone air concentrations in parts per billion" e.g. — I guess the point is to identify facilities in areas where these indicators are already showing issues?

**Comment by Frijol** [comment]
I made a nifty little definitions tool. Will break out the idea of removing/separating indicators into its own issue so we can close this one.
![image](https://github.com/ericnost/streamlit_test/assets/454690/ca8490b1-815e-413e-8085-be43e286e4b9)
