### ISSUE TITLE
Consider recategorizing types of SDWA violation

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#40]

**Comment by Frijol** [comment]
> Violation
> Documents a breach of a SDWA requirement. Violations are detected by assessment of sample results or reviews (including site visits). Violations may lead to legal actions or compliance orders. Violations are publicized, when required, by public notification. Violations may be remedied by compliance/enforcement remedies, such as improved filtration techniques or changes in procedures. SDWA violations fall into one of the following general categories:
> Health-based violations - Violations of maximum contaminant levels (MCLs) or maximum residual disinfectant levels (MRDLs), which specify the highest concentrations of contaminants or disinfectants, respectively, allowed in drinking water; or of treatment technique (TT) rules, which specify required processes intended to reduce the amounts of contaminants in drinking water. MCLs, MRDLs, and treatment technique rules are all health-based drinking water standards.
> Acute Health-Based violations - Health-based violations that have the potential to produce immediate illness.
> Monitoring and reporting (MR) violations - Failure to conduct regular monitoring of drinking water quality, as required by SDWA, or to submit monitoring results in a timely fashion to the state environmental agency or EPA.
> Public notice (PN) violations - Violations of the public notification requirements of SDWA, which require systems to immediately alert consumers if there is a serious problem with their drinking water that may pose a risk to public health.
>  Other violations - Violations of other requirements of SDWA, such as issuing annual consumer confidence reports, or conducting periodic sanitary surveys.

from the [Data Dictionary](https://echo.epa.gov/help/drinking-water-qlik-dashboard-help#vio) - do we have data on the other categories? Would be cool to see all of these

**Comment by Frijol** [comment]
For example, we might class monitoring and reporting violations as potential health violations because we just don't know

**Comment by ericnost** [comment]
> For example, we might class monitoring and reporting violations as potential health violations because we just don't know
So basically we would rename "N" as "Potentially" and explain it in a context note? Or just adding a context note describing this uncertainty.

**Comment by Frijol** [comment]
I think it would be cool to graph each of the categories out separately on the chart and then give a table of explanation. Maybe in order? Acute health-based, health-based, monitoring & reporting, public notice, other
