### ISSUE TITLE
Make decimals on top pollutors table line up evenly

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#44]
![image](https://github.com/ericnost/streamlit_test/assets/454690/a57e6dce-fe0b-423f-8ab6-2c619f89b81c)

(should we round? Are these differences in significant figures?)

**Comment by ericnost** [comment]
I guess the problem is that it will vary by pollutant and unit. .05 maybe significant for one pollutant (something light but toxic) and not another (something heavy but relatively innocuous). I wonder if there's a way we can account for that....

**Comment by Frijol** [comment]
Not using a table anymore
