### ISSUE TITLE
Size column to fit large values in top pollutors table

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#45]
![image](https://github.com/ericnost/streamlit_test/assets/454690/f61a39d4-a60e-4260-87b5-6844820500dc)

**Comment by ericnost** [comment]
I don't think there's a way to do this programmatically, though I haven't look at Streamlit's documentation for their tables. Users can resize the columns themselves, fortunately.

**Comment by Frijol** [comment]
Not using a table anymore
