### ISSUE TITLE
Change EJ percentages to %

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#47]
![image](https://github.com/ericnost/streamlit_test/assets/454690/cffe2e4c-0245-4c86-a4da-d03068f84fdc)
Seems hard and low priority but would improve legibility. Wonder if we might do it with a regex for "PCT" ending?

**Comment by ericnost** [comment]
I think it may not be too hard? I'll have to look at it again. 

I think there are "PCT" ending variables we _don't_ want though. 

Basically, for simplicity's sake at this point, I think we just show the basic percentages for socioeconomic indicators and not any of the indices or percentiles.
