### ISSUE TITLE
Consider using map only for EJ indices

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#48]
The bar graph may not be usable, since the names of census blocks will not be meaningful to users. I think the only utility the bar graph serves is to show the distribution, but I'm not sure how valuable that is/if it might be just as easy to discern on the map.
![image](https://github.com/ericnost/streamlit_test/assets/454690/b7e3b507-60e9-4646-b724-48f44f257807)

**Comment by ericnost** [comment]
That's a great point! I'm always for relying on the power of maps :)
