### ISSUE TITLE
nav buttons

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#5]
https://github.com/ericnost/streamlit_test/blob/4dfb83d05acdc96c369a97ddc383cc555d18e173/pages/1_%F0%9F%8C%8D_Statewide_Overview.py#L118

I really like the idea of using next/previous buttons to guide the user through the site. It's much better than the links on the left-hand side panel. 

The question is how to get the buttons to work correctly. I see two problems:
1. They open in new tabs. This could be addressed with `<a href="..." target="_self">asdf</a>`
2. They don't seem to open in the same *context* i.e. the data loaded in the "previous" page isn't retained. I'm wondering why this might be. a) It could be because they're opened in a new tab, so addressing 1 above would solve this. b) It could be something to do with the URL path which is currently in the form of `"/subapge"` Maybe adding the full path e.g. `https://sdwa-eew.streamlit.app/SDWA_Violations` would help?

**Comment by Frijol** [comment]
Ah, actually I have a fix but it broke the site. There's a nice page switching library that I implemented here, but though it works fine locally (and solves both issues) it didn't work on deploy. Maybe you can find the issue? https://github.com/ericnost/streamlit_test/pull/3

**Comment by Frijol** [comment]
https://github.com/ericnost/streamlit_test/pull/7
