### ISSUE TITLE
Consider breaking apart or removing environmental indicators from socioeconomic indicators

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#50]
I find it super confusing that the environmental and the socioeconomic indicators are lumped together generally. Maybe we should focus just on the socioeconomic and filter out the environmental ones for greater clarity.

I do have technical definitions for e.g. Ozone as well, though, if we did want to keep them: "Annual average of top ten maximum daily 8-hour ozone air concentrations in parts per billion" e.g. — I guess the point is to identify facilities in areas where these indicators are already showing issues? If we want to keep, maybe that would be a good additional section so we might give more context on it?

_Originally posted by @Frijol in https://github.com/ericnost/streamlit_test/issues/29#issuecomment-1633549954_

**Comment by ericnost** [comment]
I agree, I think we probably should just focus on the socioeconomic indicators. But yea, the reason to keep the environmental ones would be to give a sense of "cumulative impacts" - where might communities be facing drinking water issues _on top of_ air quality and other hazards? I think that's important to illustrate, but it would require some written context for the user.
