### ISSUE TITLE
investigate why PWS circles overlap

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#63]
<img width="122" alt="Screenshot 2023-07-21 at 1 11 12 PM" src="https://github.com/ericnost/streamlit_test/assets/6888951/db58d3a3-0a98-4a00-8def-f0261a3bc7a8">

Why is this happening? Is it because of bad EPA data or something on our end? If the former, contextualize it.

**Comment by ericnost** [comment]
I'm pretty convinced this is an EPA issue. Consider the following PWS:

NJ1922314 | 2021 | NJ | New Jersey | 2 | NTNCWS | ROLLING HILLS/LOUNSBERRY HOLLOW SCHOOL | VERNON TWP.-1922 | NJ | GW | N | Small | 1455 | 110051154111 | ROLLING HILLS/LOUNSBERRY HOLLOW SCHOOL-TREATMENT PLANT | 625 COUNTY RD 517 | VERNON | NJ | 7461 | SUSSEX | 2 | 41.245255 | -74.624567 |   |   |   |   |   |   |   | http://echo.epa.gov/detailed-facility-report?fid=110051154111
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NJ1924316 | 2021 | NJ | New Jersey | 2 | NTNCWS | HIGH POINT REG HIGH SCHO | WANTAGE TWP.-1924 | NJ | GW | N | Small | 1750 | 110049260134 | HIGH POINT REG HIGH SCHO-TREATMENT PLANT | 299 PIDGEON HILL ROAD | WANTAGE | NJ | 7461 | SUSSEX | 2 | 41.245255 | -74.624567 |   |   |   |   |   |   |   | http://echo.epa.gov/detailed-facility-report?fid=110049260134
NJ1922384 | 2021 | NJ | New Jersey | 2 | TNCWS | TALL TIMBERS CAMPGROUND  WELLS NO. 3 & 4 | VERNON TWP.-1922 | NJ | GW | N | Small | 705 | 110049264014 | TALL TIMBERS CAMPGROUND  WELLS NO. 3 & 4-TREATMENT PLANT | 100 TALL TIMBERS ROAD | VERNON | NJ | 7461 | SUSSEX | 2 | 41.245255 | -74.624567 |   |   |   |   |   |   |   | http://echo.epa.gov/detailed-facility-report?fid=110049264014
NJ1924349 | 2021 | NJ | New Jersey | 2 | TNCWS | KINGDOM HALL OF JEHOVAH WITNESS | WANTAGE TWP.-1924 | NJ | GW | N | Very Small | 50 | 110051234491 | KINGDOM HALL OF JEHOVAH WITNESS-TREATMENT PLANT | 8 PEARY DRIVE | SUSSEX | NJ | 7461 | SUSSEX | 2 | 41.245255 | -74.624567 |   |   |   |   |   |   |   | http://echo.epa.gov/detailed-facility-report?fid=110051234491

They all have the same lat/long, but they have different names, ids, addresses, etc. I don't think we could've introduced incorrect lat/long in our data pipeline; I'm pretty sure this must come upstream. We know that SDWA is notoriously bad at geo information (https://envirodatagov.org/edgi-releases-report-how-data-gaps-and-disparities-in-epa-data-undermine-climate-and-environmental-justice-screening-tools/)

**Comment by ericnost** [comment]
<img width="719" alt="Screenshot 2023-07-21 at 2 45 09 PM" src="https://github.com/ericnost/streamlit_test/assets/6888951/719bebcd-1008-40d8-82f6-c6fd1d266fe4">

If I look at these facilities in ECHO_EXPORTER I see that their lat/longs are determined by their zip code's center rather than actually geocoding the specific address :(

**Comment by ericnost** [comment]
- [ ] Write a brief section on the Statewide Overview page to explain the overlapping circles problem: EPA is bad at data.

**Comment by Frijol** [comment]
Are we able to make this more user-intuitive anyway? E.g. introduce jitter onto the map, or have it break out into several dots with lines drawn to the point as you zoom in?

**Comment by ericnost** [comment]
>  have it break out into several dots with lines drawn to the point as you zoom in?

That could be one way of showing PSA polygons and PWS points together effectively, if we cluster points. There's a fairly straightforward way to do that with folium, though I'm not sure how much load time it would save, but it would be a good way to deal with this problem. The issue is that then you lose the statewide view of patterns indicated by the different marker symbolization strategies (outline, color, size) because it'd look something like this until you zoomed in far enough and/or clicked on a cluster:
![image](https://github.com/ericnost/streamlit_test/assets/6888951/31a1cc1c-2265-4cb7-9cf7-8e6e41284b25)
(https://gis.stackexchange.com/questions/358429/specifying-shapefiles-for-clusters-and-subclusters-using-foliums-markercluster)

**Comment by ericnost** [comment]
Attempted to address this with the marker clusters....Look at some of them!
<img width="374" alt="Screenshot 2023-07-27 at 1 11 55 PM" src="https://github.com/ericnost/streamlit_test/assets/6888951/e2e9baf4-c7b8-4835-ad62-cb741a30090d">
<img width="469" alt="Screenshot 2023-07-27 at 1 28 50 PM" src="https://github.com/ericnost/streamlit_test/assets/6888951/4b28855b-0550-4916-90e1-9a08b6fc8968">
<img width="490" alt="Screenshot 2023-07-27 at 3 41 56 PM" src="https://github.com/ericnost/streamlit_test/assets/6888951/b2eb0bd3-f6fb-4b20-a82a-368d1d418393">

**Comment by ericnost** [comment]
☝️ *pretty* bad data

**Comment by Frijol** [comment]
omg. This is nuts. I can't think of anything else to try here other than just adding a note that this is an issue in their data, can you?

**Comment by ericnost** [comment]
Yea, add a note and maybe work on the styling the cluster icons: https://github.com/Leaflet/Leaflet.markercluster#all-options
