### ISSUE TITLE
change dashed/solid outline symbolization on maps

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#64]
It's hard to see the difference between dashed and solid outlines on the statewide overview. Consider a different way of symbolizing ground vs surface water.

**Comment by Frijol** [comment]
Hm, I can't see the difference between this version and the original. 
![image](https://github.com/ericnost/streamlit_test/assets/454690/4fecd4f9-fb56-4cff-9c79-8fa6a56dd0ad)
