### ISSUE TITLE
include service area polygons on statewide overview page

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#65]
IIRC, this hasn't worked in the past because it's a lot of data for the entire state, but it's worth trying.

If it doesn't work, perhaps we consider ditching the statewide overview since we've learned students will be focused on hometowns and other areas of interest rather than the overview?

**Comment by ericnost** [comment]
The map with the PSAs AND the PWS looks great but it takes > 1 minute to load. Mostly that's because some of the PSAs have very intricate boundaries and all the twists and turns add vertices, which add data, ....

<img width="546" alt="image" src="https://github.com/ericnost/streamlit_test/assets/6888951/055949a1-b5c0-4406-a7c5-42913a2678fe">

Maybe we can brainstorm what the best approach is. It might involve a deep rethink. Perhaps the first thing a user does is just draw an area of interest that returns intersecting PWS and PSA. Then they can look at violations, EJ, lead, and watershed data separately. No state overview? Or have it separate and later?

**Comment by Frijol** [comment]
I have ideas here! Idk how they would impact the load time, though.
* Can we have the PSAs invisible until you zoom in a bit?
* What if the PSAs become visible as you mouse over them, and they show not just PSA boundary but also highlight the associated PWS HQ?
* A bigger change, e.g. do we really need a statewide overview? Would it be more interesting/useful to have area selection be the first thing a user does? I noticed that this was the instinct of our stakeholders yesterday, even though it's the statewide overview page

**Comment by ericnost** [comment]
> Can we have the PSAs invisible until you zoom in a bit?
I think so, though it wouldn't have any impact on load/draw time since they would all still be drawn when `main()` runs. Could we load only the ones we need as we zoom in? Possibly but I'm not sure I know how to do that effectively here.
> What if the PSAs become visible as you mouse over them, and they show not just PSA boundary but also highlight the associated PWS HQ?
That'd be awesome. I'm not sure it's possible though from a technical perspective (or at the very least a time perspective).  Streamlit is a nifty way of interfacing between the browser DOM and Python. The folium library we're relying on takes Python inputs, spits out JS, and sends them to the DOM. Likewise, it gets back certain DOM interactions and makes them available in Python. Theoretically, hover would be one of those. I can look into it. Still doesn't address the load/draw time issue.
> do we really need a statewide overview? Would it be more interesting/useful to have area selection be the first thing a user does?
I tend to agree!

**Comment by ericnost** [comment]
also see #83
