### ISSUE TITLE
update language and instructions on SDWA violations page

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#67]
- [x] Instead of saying "select" an area we should say "draw" an area or stick with the default (Patterson)
- [x] We should indicate that the markers can be clicked on
- [x] We should include some encouraging language about persevering if things go unexpectedly (as in the demo)?
- [x] Move the "you drew a too-big box" error up so that it's visible, same with #24, and make it look more like an error warning.

**Comment by Frijol** [comment]
This is helpful. The only note I have is that the use of "select" vs "draw" makes it easier to refer to "the selected area" throughout (which we use heavily)

**Comment by ericnost** [comment]
ah, good point!
