### ISSUE TITLE
box drawing should intersect with service areas too

### ISSUE THREAD

**Issue by ericnost** [ericnost/streamlit_test#70]
Drawing a custom box should return points that fall within the boundary but also purveyor service areas polygons.

**Comment by ericnost** [comment]
One problem with this is that some of the points are also polygons. That is, the PSAs (polygons) are also PWS (points). But sometimes the points and polygons don't line up e.g. Township of Wayne service area ....due to EPA's zip code centroid approach, the point is outside the boundary.

**Comment by Frijol** [comment]
How important is the location of the PWS? Would it be more meaningful to just look at PSA? I'm not sure we're getting much by knowing where the address of the office points.

**Comment by ericnost** [comment]
Would be fixed by any of the options in #97
