### ISSUE TITLE
Consider moving Statewide Overview map under the tabs

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#83]
What if the whole statewide overview page was controlled by the category tabs, so when you pull up a map you *only* see the different sizes, or the different types? I think the current map might be trying to do too much, so gets very confusing.

Ha I think I was the one who requested that it have all this info on it originally, but I think I was wrong.

Or maybe there could be two maps on the page? First one showing clickable service area polygons so that you can find your area of interest's PWS, then the next below the tab, mapping by category?

**Comment by ericnost** [comment]
That's an interesting idea but there are two potential problems I see, one conceptual, one technical:

1. Conceptually, we need to keep in mind that there's a Venn diagram here of "purveyor service areas" (those polygons) and public water systems (PWS points/markers). Every PSA should be a public water system e.g. Trenton Water Works. But there are also PWS outside PSAs (e.g. in rural areas) and additional PWS within PSAs (institutions, gas stations, etc.) So I worry it may muddy the waters to do the PSAs upfront. I think that'd work for urban students, but we'd want to include some text that said something like "looking at a rural area? There may not be PSAs, just PWS, scroll down to check" Likewise, text that said "Looking at an urban area? There area also PWS not just this PSA"
2. From a technical perspective, I worry a little about tripling the number of maps, one for each variable (size, source water, type) but it should be ok.

**Comment by ericnost** [comment]
I'm having a hard time figuring out what this would look like in practice + implementing it technically

**Comment by Frijol** [comment]
I think we ended up going in a different direction
