### ISSUE TITLE
Change area selection to "slippy" method

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#84]
I'm wondering if it's possible to have something more like the Google Maps Offline interface, where you move/zoom the map around behind the predefined box (example:https://youtu.be/f-9Xncj1fws?t=14) so that we don't have to worry about drawing controls or boxes that are too big

**Comment by ericnost** [comment]
See also #96, #97

**Comment by Frijol** [comment]
From review today:
* Make a closer zoom correspond to selecting a tighter area (possibly it already does?)
* Give a bit of buffer so users can see (at least most of) the shapes included in the selection
