### ISSUE TITLE
Show facility violations in on EJ maps

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#88]
The EJ page promises "How do SDWA Violations relate to Environmental Justice (EJ) in the Selected Area?" but we don't actually show SDWA violations. Can we do that? I'm thinking we might overlay the points from the SDWA violations page onto the EJ maps.

**Comment by ericnost** [comment]
Circle size = # of violations, I think it should be showing? I think this is done? Will check after the server is back up.

**Comment by Frijol** [comment]
oh! I didn't know I was hitting a bug, thought we just didn't have this feature

**Comment by ericnost** [comment]
Hmm I may have exaggerated when I said "it's fixable" lol. Basically, we can't show facility violations on the EJ maps unless the user goes to the Violations page first. But we could show other markers?

**Comment by Frijol** [comment]
Hm. I'm not too concerned about this one. But do we know that we don't have them? Would be nice (not necessary) to show a note that you can go get them by going to Violations and then coming back

**Comment by ericnost** [comment]
Yes, we have them, just not on this page unless they've visited Violations. So a note about going back to Violations and then coming back would make sense.
