### ISSUE TITLE
Overset text on lead lines page

### ISSUE THREAD

**Issue by Frijol** [ericnost/streamlit_test#90]
![image](https://github.com/ericnost/streamlit_test/assets/454690/467a0ef1-1d89-4ee0-8085-8ee7fc0a5f9b)

**Comment by Frijol** [comment]
EJ page too

**Comment by ericnost** [comment]
I think this is because we hard coded the colorscale width to 750 but the map is now responsive. I'm not sure how to make a responsive colorscale bar but we could just put it in the map container or legend continaer and hope it's wide enough?

**Comment by Frijol** [comment]
I think this is fixed now?
